### ISSUE TITLE
MVエディタ 1.6.3で最大受注可能クエスト数が正常に設定できない

### ISSUE THREAD

**Issue by elleonard** [unagiootoro/RPGMZ#4]
MVのエディタにおいて、最後のプラグインパラメータの `@type` `@text` `@desc` がプラグインコマンドの定義で上書きされてしまい正常に設定できないようです。

**Comment by unagiootoro** [comment]
ご連絡くださりありがとうございます。
v1.5.3にて上記の不具合を修正いたしました。

**Comment by elleonard** [comment]
不具合が修正されていることを確認しました！
